version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - dynamodb-local
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"  # Port extern 8001, intern 8000
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb

